### ISSUE TITLE
Stage configurable

### ISSUE THREAD

**Issue by kjirou** [kjirou/escape-from-the-maze#17]
```
difficulty:
  easy:
    mazes:
      0:
        timeLimit: 120
        pickCount: 1
  normal:
  hard:
  lunatic:
  simple:
    mazes:
      0:
        timeLimit: null  # by default
        pickCount: 0  # by default
```
